from pathlib import Path


SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Space Invaders"

PLAYER_SPEED = 5
PLAYER_START_X = SCREEN_WIDTH / 2
PLAYER_START_Y = 70
PLAYER_BOUNDARY_LEFT = 32
PLAYER_BOUNDARY_RIGHT = SCREEN_WIDTH - 32

ENEMY_COUNT = 8
ENEMY_MIN_Y = 380
ENEMY_MAX_Y = 530
ENEMY_SPEED = 2
ENEMY_DROP_DISTANCE = 30

BULLET_SPEED = 8
BULLET_LIMIT = 3

GAME_OVER_LINE = 140
HUD_TEXT_SIZE = 24
TITLE_TEXT_SIZE = 38
SUBTITLE_TEXT_SIZE = 18

BASE_DIR = Path(__file__).resolve().parent.parent
ASSETS_DIR = BASE_DIR / "assets"
IMAGES_DIR = ASSETS_DIR / "images"
SOUNDS_DIR = ASSETS_DIR / "sounds"
FONTS_DIR = ASSETS_DIR / "fonts"

PLAYER_TEXTURE = IMAGES_DIR / "player" / "cohete.png"
ENEMY_TEXTURE = IMAGES_DIR / "enemies" / "enemigo.png"
PROJECTILE_TEXTURE = IMAGES_DIR / "projectiles" / "bala.png"
BACKGROUND_IMAGE = IMAGES_DIR / "ui" / "Fondo.jpg"
ICON_IMAGE = IMAGES_DIR / "ui" / "ovni.png"

BACKGROUND_MUSIC = SOUNDS_DIR / "MusicaFondo.mp3"
SHOOT_SOUND = SOUNDS_DIR / "disparo.mp3"
HIT_SOUND = SOUNDS_DIR / "Golpe.mp3"

DEFAULT_FONT = FONTS_DIR / "FreeSansBold.ttf"